name: Greeting

on:
  workflow_dispatch

env:
  NAME: My Home Lab

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Monday


    steps:
        - name: Start
          run: echo "Start GitHub Action!"
        - name: Say Hello World
          run: echo "Greeting $First_Name. Hello World from $NAME! Today is $DAY_OF_WEEK"
          env:
            First_Name: Willy
        - name: End
          run: echo "End of GitHub Action!"