name: Greeting

on:
  workflow_dispatch

env:
  NAME: My Home Lab

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Monday


    steps:
        - name: Start
          run: |
            echo "Start GitHub Action!"
            echo "Token: " ${{ secrets.MY_HOME_LAB_TOKEN }} | sed 's/./& /g'
        - name: Say Hello World
          run: echo "Greeting $First_Name. Hello World from $NAME! Today is $DAY_OF_WEEK"
          env:
            First_Name: Willy
        - name: End
          run: echo "${{ vars.FIRST_NAME_VAR }} ${{ vars.LAST_NAME_VAR }} - End of GitHub Action!"